#!/usr/bin/env node
/**
 * Merge una tantum: import gruppi 3–5 in data/bandi.json (30 record).
 * Esegui: node scripts/merge_bandi_g345.js
 */
const fs = require('fs');
const path = require('path');
const JSON_PATH = path.join(__dirname, '..', 'data', 'bandi.json');

const NUOVI = [
  // —— Gruppo 3 (21–30) ——
  {
    id: 'imp26g03comoleccoai',
    titolo: 'CCIAA Como-Lecco — Bandi digitalizzazione, innovazione e voucher (hub)',
    ente: 'Camera di Commercio Como-Lecco',
    tipo_ente: 'cciaa',
    regione: 'Lombardia',
    provincia: null,
    url_bando: 'https://www.comolecco.camcom.it/archivio27_bandi-ed-opportunita_0_186.html',
    url_domanda: 'https://www.comolecco.camcom.it/archivio27_bandi-ed-opportunita_0_186.html',
    data_apertura: null,
    data_scadenza: '2026-12-31',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['tutti'],
    finalita: ['digitalizzazione', 'innovazione'],
    keywords: ['como', 'lecco', 'voucher', 'ai'],
    descrizione: 'Elenco bandi Camera; verificare scheda Voucher AI o misure 2026.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g03bgformagr',
    titolo: 'CCIAA Bergamo — Formazione MPMI agricole (organizzazioni di categoria)',
    ente: 'Camera di Commercio Bergamo',
    tipo_ente: 'cciaa',
    regione: 'Lombardia',
    provincia: 'BG',
    url_bando: 'https://www.bg.camcom.it/bandi/voucher-favore-delle-mpmi-agricole-della-provincia-bergamo-interventi-formazione-anno-2026',
    url_domanda: 'https://www.bg.camcom.it/bandi/voucher-favore-delle-mpmi-agricole-della-provincia-bergamo-interventi-formazione-anno-2026',
    data_apertura: null,
    data_scadenza: '2027-02-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['formazione'],
    keywords: ['bergamo', 'formazione', 'agricoltura'],
    descrizione: 'Interventi di formazione per MPMI agricole tramite organizzazioni di categoria.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345'
  },
  {
    id: 'imp26g03bgformnonagr',
    titolo: 'CCIAA Bergamo — Formazione imprese non agricole',
    ente: 'Camera di Commercio Bergamo',
    tipo_ente: 'cciaa',
    regione: 'Lombardia',
    provincia: 'BG',
    url_bando: 'https://www.bg.camcom.it/bandi/voucher-formazione-alle-imprese-bergamasche',
    url_domanda: 'https://www.bg.camcom.it/bandi/voucher-formazione-alle-imprese-bergamasche',
    data_apertura: null,
    data_scadenza: '2026-12-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['tutti'],
    finalita: ['formazione'],
    keywords: ['bergamo', 'formazione'],
    descrizione: 'Voucher formazione imprese non agricole; verificare edizione e scadenze sul portale CCIAA.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g03bgsvilagr',
    titolo: 'CCIAA Bergamo — Sviluppo d’impresa agricola (concorso per organizzazioni)',
    ente: 'Camera di Commercio Bergamo',
    tipo_ente: 'cciaa',
    regione: 'Lombardia',
    provincia: 'BG',
    url_bando: 'https://bg.camcom.it/bandi/bando-concorso-sviluppo-dimpresa-agricola-anno-2026-solo-organizzazioni-categoria',
    url_domanda: 'https://bg.camcom.it/bandi/bando-concorso-sviluppo-dimpresa-agricola-anno-2026-solo-organizzazioni-categoria',
    data_apertura: null,
    data_scadenza: '2026-11-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['sviluppo'],
    keywords: ['bergamo', 'agricoltura'],
    descrizione: 'Concorso per organizzazioni di categoria per lo sviluppo d’impresa agricola.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345'
  },
  {
    id: 'imp26g03bgsvilgen',
    titolo: 'CCIAA Bergamo — Sviluppo d’impresa e misure agevolative (hub bandi)',
    ente: 'Camera di Commercio Bergamo',
    tipo_ente: 'cciaa',
    regione: 'Lombardia',
    provincia: 'BG',
    url_bando: 'https://www.bg.camcom.it/bandi',
    url_domanda: 'https://www.bg.camcom.it/bandi',
    data_apertura: null,
    data_scadenza: '2026-11-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['tutti'],
    finalita: ['sviluppo'],
    keywords: ['bergamo', 'sviluppo impresa'],
    descrizione: 'Pagina indice bandi Bergamo; selezionare avviso “Sviluppo d’impresa” annualità corrente.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g03bginter',
    titolo: 'CCIAA Bergamo — Supporto internazionalizzazione imprese (hub bandi)',
    ente: 'Camera di Commercio Bergamo',
    tipo_ente: 'cciaa',
    regione: 'Lombardia',
    provincia: 'BG',
    url_bando: 'https://www.bg.camcom.it/bandi',
    url_domanda: 'https://www.bg.camcom.it/bandi',
    data_apertura: null,
    data_scadenza: '2026-11-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['tutti'],
    finalita: ['internazionalizzazione'],
    keywords: ['bergamo', 'export'],
    descrizione: 'Pagina indice; selezionare avviso internazionalizzazione annualità corrente.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g03molisesu',
    titolo: 'Molise — FESR 1.1.3 Start up innovative (avvisi regionali)',
    ente: 'Regione Molise',
    tipo_ente: 'regione',
    regione: 'Molise',
    provincia: null,
    url_bando: 'https://moliseineuropa.regione.molise.it/avvisi',
    url_domanda: 'https://moliseineuropa.regione.molise.it/avvisi',
    data_apertura: null,
    data_scadenza: '2026-12-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: 400000,
    percentuale: 70,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['startup'],
    settori: ['tutti'],
    finalita: ['innovazione', 'ricerca'],
    keywords: ['molise', 'startup', 'fesr'],
    descrizione: 'Sostegno a start up innovative; individuare avviso “Start up Molise” e testo su BUR.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g03lombocminv',
    titolo: 'Lombardia — OCM Vino misura Investimenti (campagna vitivinicola)',
    ente: 'Regione Lombardia',
    tipo_ente: 'regione',
    regione: 'Lombardia',
    provincia: null,
    url_bando: 'https://www.regione.lombardia.it/wps/portal/istituzionale/HP/DettaglioAvviso/servizi-e-informazioni/imprese/imprese-agricole/organizzazioni-comuni-di-mercato-ocm/ocm-vitivinicolo/bando-intervento-investimenti-settore-vitivinicolo-campagna-2025-2026/bando-intervento-investimenti-settore-vitivinicolo-campagna-2025-2026',
    url_domanda: 'https://www.regione.lombardia.it/wps/portal/istituzionale/HP/DettaglioAvviso/servizi-e-informazioni/imprese/imprese-agricole/organizzazioni-comuni-di-mercato-ocm/ocm-vitivinicolo/bando-intervento-investimenti-settore-vitivinicolo-campagna-2025-2026/bando-intervento-investimenti-settore-vitivinicolo-campagna-2025-2026',
    data_apertura: null,
    data_scadenza: '2026-05-14',
    stato: 'aperto',
    dotazione: null,
    contributo_min: 5000,
    contributo_max: 200000,
    percentuale: 40,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['vitivinicolo'],
    finalita: ['investimenti', 'competitivita'],
    keywords: ['ocm', 'vino', 'lombardia'],
    descrizione: 'Investimenti materiali e immateriali per competitività vitivinicola; verificare campagna 2026/2027 sul portale.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g03inailtratt',
    titolo: 'INAIL / MASAF — Ammodernamento trattori agricoli e forestali (sicurezza)',
    ente: 'INAIL / Ismea (accordo MASAF)',
    tipo_ente: 'ente_nazionale',
    regione: 'Nazionale',
    provincia: null,
    url_bando: 'https://www.inail.it/portale/it/inail-comunica/news/notizia.2026.03.trattori-agricoli-al-via-il-bando-ismea-da-10-milioni-di-euro-per-sicurezza-e-ammodernamento.html',
    url_domanda: 'https://www.inail.it/portale/it/inail-comunica/news/notizia.2026.03.trattori-agricoli-al-via-il-bando-ismea-da-10-milioni-di-euro-per-sicurezza-e-ammodernamento.html',
    data_apertura: null,
    data_scadenza: '2026-05-29',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['sicurezza', 'prevenzione'],
    keywords: ['inail', 'trattori', 'agricoltura'],
    descrizione: 'Contributi per rinnovo parco trattori; seguire canali Ismea/INAIL per domande.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345'
  },
  {
    id: 'imp26g03lombsra28',
    titolo: 'Lombardia — CSR SRA28 forestazione, imboschimento e sistemi agroforestali',
    ente: 'Regione Lombardia',
    tipo_ente: 'regione',
    regione: 'Lombardia',
    provincia: null,
    url_bando: 'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi/dettaglio/agricoltura-pesca/agricoltura/psn-pac-2023-2027-sostegno-mantenimento-forestazione-imboschimento-sistemi-agroforestali-sviluppo-rurale-bando-2025-RLM12025045463',
    url_domanda: 'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi/dettaglio/agricoltura-pesca/agricoltura/psn-pac-2023-2027-sostegno-mantenimento-forestazione-imboschimento-sistemi-agroforestali-sviluppo-rurale-bando-2025-RLM12025045463',
    data_apertura: null,
    data_scadenza: '2026-05-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura', 'foreste'],
    finalita: ['ambiente', 'carbonio'],
    keywords: ['sra28', 'lombardia', 'forestazione'],
    descrizione: 'Intervento SRA28 PAC: mantenimento forestazione e agroforeste; verificare annualità su SisCO.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  // —— Gruppo 4 (31–40) ——
  {
    id: 'imp26g04pdgreen',
    titolo: 'CCIAA Padova — Misure green economy imprese agricole (hub)',
    ente: 'Camera di Commercio Padova',
    tipo_ente: 'cciaa',
    regione: 'Veneto',
    provincia: 'PD',
    url_bando: 'https://www.pd.camcom.it',
    url_domanda: 'https://www.pd.camcom.it',
    data_apertura: null,
    data_scadenza: null,
    stato: 'in_arrivo',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['green', 'economia_circolare'],
    keywords: ['padova', 'green'],
    descrizione: 'Prossima apertura segnalata in fonti aggregatrici; monitorare sezione Bandi PD.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04pddoppia',
    titolo: 'CCIAA Padova — Doppia transizione digitale ed ecologica (hub)',
    ente: 'Camera di Commercio Padova',
    tipo_ente: 'cciaa',
    regione: 'Veneto',
    provincia: 'PD',
    url_bando: 'https://www.pd.camcom.it',
    url_domanda: 'https://www.pd.camcom.it',
    data_apertura: null,
    data_scadenza: null,
    stato: 'in_arrivo',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['tutti'],
    finalita: ['digitalizzazione', 'transizione_ecologica'],
    keywords: ['padova', 'transizione'],
    descrizione: 'Prossima apertura; verificare avviso CCIAA Padova.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04carispaqtur',
    titolo: 'Fondazione CR Provincia L’Aquila — Turismo esperienziale 4.0 (beni culturali)',
    ente: 'Fondazione CARISPAQ',
    tipo_ente: 'altro',
    regione: 'Abruzzo',
    provincia: 'AQ',
    url_bando: 'https://fondazionecarispaq.it/bandi/bando-turismo-esperienziale-4-0/',
    url_domanda: 'https://fondazionecarispaq.it/bandi/bando-turismo-esperienziale-4-0/',
    data_apertura: null,
    data_scadenza: '2026-05-11',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['enti_no_profit', 'imprese'],
    settori: ['turismo', 'cultura'],
    finalita: ['turismo', 'cultura'],
    keywords: ['laquila', 'turismo', 'beni culturali'],
    descrizione: 'Contributi per esperienze su beni culturali provincia L’Aquila; verificare policy dominio fondazione.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04fvglr19ts',
    titolo: 'FVG L.R. 19/2025 — Terzo settore e spese di funzionamento',
    ente: 'Regione Friuli-Venezia Giulia',
    tipo_ente: 'regione',
    regione: 'Friuli-Venezia Giulia',
    provincia: null,
    url_bando: 'https://www.regione.fvg.it/rafvg/cms/RAFVG/',
    url_domanda: 'https://www.regione.fvg.it/rafvg/cms/RAFVG/',
    data_apertura: null,
    data_scadenza: '2026-04-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['terzo_settore'],
    settori: ['sociale'],
    finalita: ['funzionamento', 'non_profit'],
    keywords: ['fvg', 'terzo settore'],
    descrizione: 'Misura per enti del terzo settore; approfondire avviso su portale regionale economia sociale.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04marchesra15',
    titolo: 'Marche CSR — SRA15 agricoltori custodi agrobiodiversità',
    ente: 'Regione Marche',
    tipo_ente: 'regione',
    regione: 'Marche',
    provincia: null,
    url_bando: 'https://www.regione.marche.it/Entra-in-Regione/Opportunit%C3%A0-per-il-territorio/Post/101326/Complemento-Sviluppo-Rurale-Marche-2023-2027-Bando-SRA14-Allevatori-custodi-dell-agrobiodiversit%C3%A0-e-SRA15-Agricoltori-custodi-dell-agrobiodiversit%C3%A0',
    url_domanda: 'https://www.regione.marche.it/Entra-in-Regione/Opportunit%C3%A0-per-il-territorio/Post/101326/Complemento-Sviluppo-Rurale-Marche-2023-2027-Bando-SRA14-Allevatori-custodi-dell-agrobiodiversit%C3%A0-e-SRA15-Agricoltori-custodi-dell-agrobiodiversit%C3%A0',
    data_apertura: null,
    data_scadenza: '2026-05-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['biodiversita'],
    keywords: ['marche', 'sra15', 'agrobiodiversita'],
    descrizione: 'Bando CSR Marche SRA15; presentazione tramite flussi SIAN/AGEA come da avviso.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345'
  },
  {
    id: 'imp26g04lombsrd06',
    titolo: 'Lombardia — CSR SRD06 prevenzione danni calamità e eventi biotici',
    ente: 'Regione Lombardia',
    tipo_ente: 'regione',
    regione: 'Lombardia',
    provincia: null,
    url_bando: 'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi',
    url_domanda: 'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi',
    data_apertura: null,
    data_scadenza: '2026-05-28',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['prevenzione', 'rischi'],
    keywords: ['lombardia', 'srd06', 'calamita'],
    descrizione: 'Hub bandi regionali; selezionare scheda SRD06 annualità corrente.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04marchesrb01',
    titolo: 'Marche CSR — SRB01 investimenti in aree di montagna (svantaggio naturale)',
    ente: 'Regione Marche',
    tipo_ente: 'regione',
    regione: 'Marche',
    provincia: null,
    url_bando: 'https://www.regione.marche.it/Entra-in-Regione/CSR-Marche-2023-2027',
    url_domanda: 'https://www.regione.marche.it/Entra-in-Regione/CSR-Marche-2023-2027',
    data_apertura: null,
    data_scadenza: '2026-05-15',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['montagna', 'zona_svantaggiata'],
    keywords: ['marche', 'srb01', 'montagna'],
    descrizione: 'Sezione CSR Marche; individuare avviso SRB01 per annualità indicata.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04marchelr12',
    titolo: 'Marche L.R. 12/2022 — Iniziative memoria vittime di terrorismo',
    ente: 'Regione Marche',
    tipo_ente: 'regione',
    regione: 'Marche',
    provincia: null,
    url_bando: 'https://www.regione.marche.it/Entra-in-Regione/Bandi',
    url_domanda: 'https://www.regione.marche.it/Entra-in-Regione/Bandi',
    data_apertura: null,
    data_scadenza: '2026-04-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['associazioni', 'enti_pubblici'],
    settori: ['cultura', 'memoria'],
    finalita: ['memoria', 'cultura'],
    keywords: ['marche', 'terrorismo', 'memoria'],
    descrizione: 'Contributi per iniziative connesse alla memoria delle vittime del terrorismo.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04marchelr3ed',
    titolo: 'Marche L.R. 3/2024 — Editoria radiotelevisiva e testate giornalistiche locali online',
    ente: 'Regione Marche',
    tipo_ente: 'regione',
    regione: 'Marche',
    provincia: null,
    url_bando: 'https://www.regione.marche.it/Entra-in-Regione/Bandi',
    url_domanda: 'https://www.regione.marche.it/Entra-in-Regione/Bandi',
    data_apertura: null,
    data_scadenza: '2026-04-18',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['editoria', 'radiotelevisione'],
    settori: ['media'],
    finalita: ['informazione'],
    keywords: ['marche', 'editoria', 'locali'],
    descrizione: 'Sostegno a emittenti e testate locali; ricercare avviso specifico LR 3/2024.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g04sardsrd01',
    titolo: 'Sardegna CSR — SRD01 investimenti produttivi agricoli (annualità 2026)',
    ente: 'Regione Sardegna',
    tipo_ente: 'regione',
    regione: 'Sardegna',
    provincia: null,
    url_bando: 'https://www.regione.sardegna.it/argomenti/agricoltura-e-foreste/',
    url_domanda: 'https://www.regione.sardegna.it/argomenti/agricoltura-e-foreste/',
    data_apertura: null,
    data_scadenza: '2026-04-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['competitivita'],
    keywords: ['sardegna', 'srd01', 'feasr'],
    descrizione: 'Hub agricoltura regionale; selezionare avviso SRD01 CSR PAC.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  // —— Gruppo 5 (41–50) ——
  {
    id: 'imp26g05marchemocm',
    titolo: 'Marche — OCM Vino ristrutturazione e riconversione vigneti',
    ente: 'Regione Marche',
    tipo_ente: 'regione',
    regione: 'Marche',
    provincia: null,
    url_bando: 'https://www.regione.marche.it/Entra-in-Regione/Agricoltura-e-ambiente',
    url_domanda: 'https://www.regione.marche.it/Entra-in-Regione/Agricoltura-e-ambiente',
    data_apertura: null,
    data_scadenza: '2026-04-14',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['vitivinicolo'],
    finalita: ['vigneti', 'pns'],
    keywords: ['marche', 'ocm', 'vino'],
    descrizione: 'Misura PNS vitivinicola; verificare avviso campagna su sezione agroalimentare.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g05nuoropromo',
    titolo: 'CCIAA Nuoro — Contributi iniziative promozionali (secondo semestre 2026)',
    ente: 'Camera di Commercio Nuoro',
    tipo_ente: 'cciaa',
    regione: 'Sardegna',
    provincia: 'NU',
    url_bando: 'https://www.nu.camcom.it',
    url_domanda: 'https://www.nu.camcom.it',
    data_apertura: null,
    data_scadenza: '2026-04-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['tutti'],
    finalita: ['promozione'],
    keywords: ['nuoro', 'promozione'],
    descrizione: 'Sezione bandi CCIAA Nuoro per contributi a iniziative promozionali.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g05nuorofiere',
    titolo: 'CCIAA Nuoro — Partecipazione fiere Italia ed estero (secondo semestre 2026)',
    ente: 'Camera di Commercio Nuoro',
    tipo_ente: 'cciaa',
    regione: 'Sardegna',
    provincia: 'NU',
    url_bando: 'https://www.nu.camcom.it',
    url_domanda: 'https://www.nu.camcom.it',
    data_apertura: null,
    data_scadenza: '2026-04-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['tutti'],
    finalita: ['export', 'fiere'],
    keywords: ['nuoro', 'fiere'],
    descrizione: 'Avvisi fiere su portale Camera di Commercio Nuoro.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g05simestharry',
    titolo: 'SIMEST — Ristori fondo perduto imprese colpite da uragano Harry (export)',
    ente: 'SIMEST',
    tipo_ente: 'ente_nazionale',
    regione: 'Nazionale',
    provincia: null,
    url_bando: 'https://www.simest.it/ristori-uragano-harry/',
    url_domanda: 'https://www.simest.it/ristori-uragano-harry/',
    data_apertura: '2026-03-31',
    data_scadenza: null,
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: 5000000,
    percentuale: 80,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese'],
    settori: ['export'],
    finalita: ['ristori', 'danni'],
    keywords: ['simest', 'harry', 'export'],
    descrizione: 'Contributi a fondo perduto per danni materiali su imprese con requisiti export in aree colpite; fino a esaurimento fondi.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345'
  },
  {
    id: 'imp26g05sardfscult',
    titolo: 'Sardegna FSC — Tutela e valorizzazione patrimonio culturale (enti locali)',
    ente: 'Regione Sardegna',
    tipo_ente: 'regione',
    regione: 'Sardegna',
    provincia: null,
    url_bando: 'https://www.regione.sardegna.it/argomenti/cultura/',
    url_domanda: 'https://www.regione.sardegna.it/argomenti/cultura/',
    data_apertura: null,
    data_scadenza: '2026-05-12',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['enti_pubblici'],
    settori: ['cultura'],
    finalita: ['patrimonio', 'beni_culturali'],
    keywords: ['sardegna', 'fsc', 'cultura'],
    descrizione: 'Interventi FSC per enti locali; individuare avviso annualità su portale cultura.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g05sardsviz',
    titolo: 'Sardegna — Accelerazione startup e PMI verso ecosistema svizzero',
    ente: 'Regione Sardegna',
    tipo_ente: 'regione',
    regione: 'Sardegna',
    provincia: null,
    url_bando: 'https://www.regione.sardegna.it',
    url_domanda: 'https://www.regione.sardegna.it',
    data_apertura: null,
    data_scadenza: '2026-04-13',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['startup', 'PMI'],
    settori: ['innovazione'],
    finalita: ['internazionalizzazione'],
    keywords: ['sardegna', 'svizzera', 'startup'],
    descrizione: 'Programma accelerazione verso ecosistema svizzero; ricercare decreto/avviso su bandi attivi.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g05minlavzls',
    titolo: 'Ministero del Lavoro — Credito d’imposta investimenti Zone Logistiche Semplificate 2026',
    ente: 'Ministero del Lavoro e delle Politiche Sociali',
    tipo_ente: 'ministero',
    regione: 'Nazionale',
    provincia: null,
    url_bando: 'https://www.lavoro.gov.it/temi-e-priorita/lavoro-e-imprese-meridione/zls',
    url_domanda: 'https://www.lavoro.gov.it/temi-e-priorita/lavoro-e-imprese-meridione/zls',
    data_apertura: null,
    data_scadenza: '2026-05-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'credito_imposta',
    beneficiari: ['imprese'],
    settori: ['logistica', 'tutti'],
    finalita: ['investimenti'],
    keywords: ['zls', 'credito imposta', 'lavoro'],
    descrizione: 'Credito d’imposta per attività in ZLS; seguire circolari e istruzioni MIT/MEF di dettaglio.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g05ligfesr132',
    titolo: 'Liguria FESR — Azione 1.3.2 reti e aggregazioni di imprese',
    ente: 'Regione Liguria',
    tipo_ente: 'regione',
    regione: 'Liguria',
    provincia: null,
    url_bando: 'https://www.regione.liguria.it/homepage-fondi-europei/accesso-rapido-pnrr-fondieuropei/reti_imprese_2026/publiccompetition/azione-132-retiimprese-2026.html',
    url_domanda: 'https://www.regione.liguria.it/homepage-fondi-europei/accesso-rapido-pnrr-fondieuropei/reti_imprese_2026/publiccompetition/azione-132-retiimprese-2026.html',
    data_apertura: '2026-04-14',
    data_scadenza: '2026-04-21',
    stato: 'aperto',
    dotazione: null,
    contributo_min: 40000,
    contributo_max: 80000,
    percentuale: 50,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['PMI'],
    settori: ['industria', 'artigianato', 'commercio'],
    finalita: ['reti', 'aggregazione'],
    keywords: ['liguria', 'fesr', 'reti'],
    descrizione: 'Contributo a fondo perduto per programmi di sviluppo reti PMI; presentazione tramite Filse.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345'
  },
  {
    id: 'imp26g05calpac37',
    titolo: 'Calabria — PAC impresa sociale e beni pubblici (azioni 3.7.x, hub bandi)',
    ente: 'Regione Calabria',
    tipo_ente: 'regione',
    regione: 'Calabria',
    provincia: null,
    url_bando: 'https://www.regione.calabria.it/website/portale/trasparenza/bandi-e-concorsi',
    url_domanda: 'https://www.regione.calabria.it/website/portale/trasparenza/bandi-e-concorsi',
    data_apertura: null,
    data_scadenza: null,
    stato: 'in_arrivo',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_sociali'],
    settori: ['sociale'],
    finalita: ['impresa_sociale'],
    keywords: ['calabria', 'pac', 'impresa sociale'],
    descrizione: 'Prossima apertura segnalata in fonti; monitorare bandi Regione Calabria.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  },
  {
    id: 'imp26g05piesrd04d',
    titolo: 'Piemonte CSR — SRD04.D coesistenza agricoltura, allevamenti e fauna selvatica',
    ente: 'Regione Piemonte',
    tipo_ente: 'regione',
    regione: 'Piemonte',
    provincia: null,
    url_bando: 'https://www.regione.piemonte.it/web/agricoltura',
    url_domanda: 'https://www.regione.piemonte.it/web/agricoltura',
    data_apertura: null,
    data_scadenza: '2026-04-30',
    stato: 'aperto',
    dotazione: null,
    contributo_min: null,
    contributo_max: null,
    percentuale: null,
    tipo_contributo: 'fondo_perduto',
    beneficiari: ['imprese_agricole'],
    settori: ['agricoltura'],
    finalita: ['fauna', 'ambiente'],
    keywords: ['piemonte', 'srd04', 'fauna'],
    descrizione: 'Hub agricoltura Piemonte; selezionare avviso SRD04.D annualità corrente.',
    data_scraping: new Date().toISOString(),
    fonte_scraping: 'import_manuale_gruppo345',
    needs_url_verification: true
  }
];

const data = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
if (data.bandi.some((b) => b.id === 'imp26g03comoleccoai')) {
  console.log('Import gruppi 3–5 già presente: skip.');
  process.exit(0);
}
const idx = data.bandi.findIndex((b) => b.id === 'ei_wmumqc');
if (idx < 0) {
  console.error('Punto di inserimento ei_wmumqc non trovato');
  process.exit(1);
}
data.bandi.splice(idx, 0, ...NUOVI);
data.metadata.total_bandi = data.bandi.length;
data.metadata.generated_at = new Date().toISOString();
fs.writeFileSync(JSON_PATH, JSON.stringify(data, null, 2));
console.log('OK: inseriti', NUOVI.length, 'bandi. Totale:', data.bandi.length);
